stages:
  - code-quality

image: php:8.0

# rector testing
rector:
  stage: code-quality
  image: composer:2.1
  only:
    - pushes
  script:
    - composer require --dev ssch/typo3-rector
    - ls -la vendor
    - ls -la vendor/bin
    - vendor/bin/rector process --help
    - vendor/bin/rector process --config config/rector.php --dry-run --debug  


publish-to-ter:
  stage: release
  image: composer:2
  only:
    - tags
  before_script:
    - composer global require typo3/tailor
  script:
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$TYPO3_API_TOKEN" ] && [ -n "$TYPO3_EXTENSION_KEY" ]; then
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        /tmp/vendor/bin/tailor ter:publish --comment "$TAG_MESSAGE" "$CI_COMMIT_TAG" "$TYPO3_EXTENSION_KEY"
      fi;