services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Treupo\SysNoteWidgets\:
    resource: '../Classes/*'

  dashboard.widget.sys_notes.default:
    class: 'Treupo\SysNoteWidgets\Widgets\PageOverviewWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@Treupo\SysNoteWidgets\Widgets\Provider\PagesWithInternalNoteToDosDataProvider'
      $options:
        category: 0
        template: 'Widget/PagesWithInternalNote'
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_default'
        groupNames: 'treupo_sys_note_widgets'
        title: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteDefault.title'
        description: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteDefault.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.instructions:
    class: 'Treupo\SysNoteWidgets\Widgets\PageOverviewWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@Treupo\SysNoteWidgets\Widgets\Provider\PagesWithInternalNoteToDosDataProvider'
      $options:
        category: 1
        template: 'Widget/PagesWithInternalNote'
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_instructions'
        groupNames: 'treupo_sys_note_widgets'
        title: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteInstructions.title'
        description: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteInstructions.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.template:
    class: 'Treupo\SysNoteWidgets\Widgets\PageOverviewWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@Treupo\SysNoteWidgets\Widgets\Provider\PagesWithInternalNoteToDosDataProvider'
      $options:
        category: 2
        template: 'Widget/PagesWithInternalNote'
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_template'
        groupNames: 'treupo_sys_note_widgets'
        title: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteTemplate.title'
        description: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteTemplate.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.notes:
    class: 'Treupo\SysNoteWidgets\Widgets\PageOverviewWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@Treupo\SysNoteWidgets\Widgets\Provider\PagesWithInternalNoteToDosDataProvider'
      $options:
        template: 'Widget/PagesWithInternalNote'
        category: 3
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_notes'
        groupNames: 'treupo_sys_note_widgets'
        title: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteNotes.title'
        description: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteNotes.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.todos:
    class: 'Treupo\SysNoteWidgets\Widgets\PageOverviewWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@Treupo\SysNoteWidgets\Widgets\Provider\PagesWithInternalNoteToDosDataProvider'
      $options:
        template: 'Widget/PagesWithInternalNote'
        category: 4
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_todos'
        groupNames: 'treupo_sys_note_widgets'
        title: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteToDos.title'
        description: 'LLL:EXT:treupo_sys_note_widgets/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteToDos.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'
